### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by yuyijie1995** [smallcorgi/3D-Deepbox#32]
Epoch 1 : Loss:0.0:   0%|          | 0/1978 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/wrc/下载/pycharm-2018.2.5/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/wrc/下载/pycharm-2018.2.5/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/wrc/下载/pycharm-2018.2.5/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/wrc/下载/pycharm-2018.2.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/wrc/yuyijie/3d_detec/3D-Deepbox/main.py", line 282, in <module>
    train(args.image, args.box2d, args.label)
  File "/home/wrc/yuyijie/3d_detec/3D-Deepbox/main.py", line 168, in train
    train_img, train_label = train_gen.next()
AttributeError: 'generator' object has no attribute 'next'

I inputed  --mode train --gpu 0 --image /home/wrc/yuyijie/3d_detec/3D-Deepbox/training/image_2/ --label /home/wrc/yuyijie/3d_detec/3D-Deepbox/training/label_2/ --box2d /home/wrc/yuyijie/3d_detec/3D-Deepbox/training/label_2/ as parameters but this error happened,what should I do

**Comment by scnuhealthy** [comment]
use python2 or next(train_gen)

**Comment by yuyijie1995** [comment]
thanks a lot
